TYPE_IMAGES =          'images'
TYPE_DESIGN =          'design'
TYPE_PYTHON =          'python'
TYPE_PRESENTATION =    'presentation'
TYPE_SCRATCH =         'scratch'
TYPE_WEBSITE =         'website'
TYPE_GAMEDESIGN =      'gamedesign'
TYPE_UNITY =           'unity'
TYPE_VIDEO =           'video'
TYPE_VSCODE =          'vscode'

RELATIONSHIP_FOLLOW =  'follow'
RELATIONSHIP_FRIEND =  'friend'

SHARING_MODE_PRIVATE = 'private'
SHARING_MODE_GROUP =   'group'
SHARING_MODE_PUBLIC =  'universe'

REACTION_LOVE =        'love'
REACTION_LIKE =        'like'
REACTION_FIRE =        'fire'

SORT_LATEST =          'id'
SORT_COMMENT_COUNT =   'comments_count'
SORT_BEST =            'best'